create table if not exists public.agent_messages (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.agent_messages enable row level security;

-- The Vercel serverless function writes with SUPABASE_SERVICE_ROLE_KEY.
-- No public read/write policy is intentionally created for this private log.
